### ISSUE TITLE
 Se puede entregar sin archivos .h

### ISSUE THREAD

**Issue by FdelMazo** [algoritmos-rw/corrector#21]
Ejemplo: https://github.com/algoritmos-rw/algo2_entregas/tree/master/lista/2018_2/102731

La lista hay que entregarla ya con el `.h`, pero un alumno no lo incluyo en el zip y aun así funcionó (lo cual tiene sentido porque pisamos sus headers), pero no debería porque es parte obligatoria de la entrega.

**Comment by mbuchwald** [comment]
No creo que valga el esfuerzo corregir esto (aunque creo que con Go se sostendría el problema en sí)

**Comment by FdelMazo** [comment]
Graicas por verlo!
