### ISSUE TITLE
Regenerar los secrets

### ISSUE THREAD

**Issue by FdelMazo** [algoritmos-rw/corrector#27]
Así los valores de CORRECTOR_OAUTH_SECRET en previos commits pasan a ser invalidos (y obviamente, no recommitearlos)

**Comment by dato** [comment]
Y revocar los antiguos, si no se hace automáticamente.

**Comment by dato** [comment]
_Creo_ que capaz haya otras cosas usando el mismo Client ID (básicamente, cualquier cosa que esté hablando con Google?). De hecho, habría que ver si en Algoritmos 1 no están usando los mismos (tanto en su corrector como su consultar notas, y no sé si algo más; hay que hablar con @dessaya). De nuestro lado supongo que sería: corrector, consultar notas y sistema de entregas.

**Comment by dato** [comment]
Alguno puede hacerse responsable de esto, con mi ayuda? @FdelMazo @ndvazquez

**Comment by dato** [comment]
Básicamente hay que entrar a la Developers Console de Google desde las 2 cuentas de Gmail. Si no recuerdo mal, el Client ID estará asociado a la de Algoritmos 1.

Habría que crear uno nuevo desde `tps.7540rw@gmail.com`, que la gente de Algoritmos 1 actualice sus cosas (incluyendo todos los refresh tokens), y revocar el antiguo.

Luego, para tener las cosas separadas, habría que crear otro distinto desde `tps.7541rw@gmail.com`; seguramente la consola de esa cuenta no tenga nada.

Si se me olvida algo, lo voy diciendo por aquí.

**Comment by FdelMazo** [comment]
Actualizado el client_secret de tps.7541rw, el único commiteado en este repo.
