### ISSUE TITLE
Definición de cuatrimestres estática

### ISSUE THREAD

**Issue by mbuchwald** [algoritmos-rw/corrector#38]
Hoy en día la definición de que una entrega está siendo durante el primer o segundo cuatrimestre es en base a _saber_ más o menos fechas de inicio y fin de cuatrimestre, cosa que no se va a cumplir en 2020 (y potencialmente inicios de 2021). Esto respecto a [los directorios de github](https://github.com/algoritmos-rw/corrector/blob/master/corrector.py#L190)
Ver si hay alguna forma _elegante_ de resolver esto, sino sale hack en dicha función.

**Comment by dato** [comment]
Esto ya se está haciendo en https://github.com/algoritmos-rw/algo2_sistema_entregas
