### ISSUE TITLE
Auto-creación de pull requests para corrección

### ISSUE THREAD

**Issue by dato** [algoritmos-rw/corrector#40]
En este _issue_ describo brevemente mi plan parar semi-automatizar la creación de pull requests para la corrección de TPs. Es algo que a mí, Dato, me urge este cuatrimestre y por eso le doy prioridad justo ahora.

>**Nota:** siempre tuve un plan más ambicioso para esto (con una app de Github, auto-apertura de PRs, etc.), pero —dada la cursada virtual— estoy agilizando ahora _a por el plan más sencillo_ porque no quiero corregir {no papel, no PR}.

-----

**Objetivo:** Para entregas de alumnos seleccionados (esto es, marcados en la planilla como tal), cada entrega se guardará en un repositorio asociado al alumno y —tras el primer “Todo OK”— se le sugerirá una URL donde puede crear un pull request para la corrección.

**Planilla:** Hay una hoja llamada _fiubatp_ que el corrector consultará. Si una fila tiene un usuario de Github + un repo asociado, no solo hará push de la entrega al repo global, sino que también lo hará a ese repo (con un esquema de branches específico).

**No se realizarán de manera automática:** la creación de repos (aunque habrá un script) ni la creación de pull requests (más allá de incluir la URL en el correo). En una primera fase, tampoco el corrector contactará con Google Sheets, sino que usará un CSV exportado.

**No es un objetivo en este momento:** diseñar algo que sea compatible con alumnos que preferirían usar Git por su cuenta y hacer las entregas vía _git push_. Por el momento, el único mecanismo de entregas es la página de entregas.
  - [x] Consecuencia: investigar si se puede quitar acceso push al repo, y aun así permitir abrir pull requests.

-----

Pasos/TODO items:

 - [x] crear un repositorio en el que se basarán las entregas (p.ej. `algoritmos-rw/algo2_alu_skel`)
    - [x] quizás crear un script que pueda crear este repo a partir de _algo2_skel_ (https://github.com/algoritmos-rw/algo2_skel/pull/189)

- [x] escribir un módulo del corrector _pulrequest.py_ que, oportunísticamente, añada los archivos de la entrega al repositorio (si lo hay) y, si corresponde, inyecte en el mail la URL de creación del pull request para ese TP

- [ ] escribir una página documentando brevemente el funcionamiento (para que el docente que use el sistema pueda compartir con sus corregides)

-----
Espero tener esto andando para la fecha de apertura del TP0 (famous last words). Beta-testers welcome.

**Comment by mbuchwald** [comment]
> Consecuencia: investigar si se puede quitar acceso push al repo, y aun así permitir abrir pull requests.
Se podría protegiendo el branch master, o no?

**Comment by dato** [comment]
>Se podría protegiendo el branch master, o no?

Comprobado que se puede asignando nivel de acceso **Triage** (a mitad de camino entre Read y Write).

**Comment by dato** [comment]
v1.0 funcionando as of today.
