### ISSUE TITLE
Elegir estrategia de historial para repos individuales (¿squash?)

### ISSUE THREAD

**Issue by dato** [algoritmos-rw/corrector#44]
Con @NachoRaik y @mbuchwald hablamos que quizás no sea tan buena idea producir un commit por cada entrega (incluso fallida), sobre todo según nos vayamos acercando a entregas más complejas. Para el historial detallado, ya está [algo2_entregas](https://github.com/algoritmos-rw/algo2_entregas).

Al principio no me convenció mucho pero, pensándolo mejor, podría simplificar _bastante_ el código, porque no habría que comparar y reescribir historiales (un lindo ejercicio, pero tedioso), tan solo sobreescribir con los archivos de la última entrega (corrector.py controlaría de solo llamar en "Todo OK", como se hace ahora; pero solo se crearía un commit). Además se solucionaría #43.

La contrapartida es no poder mirar/comentar en el PR por qué algo no está funcionando, y tener que hacerlo por correo. Es lo único que me disgusta.

**Comment by NachoRaik** [comment]
Para el caso excepcional de comentar el PR que no funciona, tengo 2 preguntas:

1. No se podría ejecutar a mano el script para que haga el PR aun no teniendo el TODO OK? opciones serian capaz refactorizar un poco el codigo para que:
    - El script que manda el PR no quede hookeado al que chequee el TODO OK, cosa que se pueda hacer aun sin obtenerlo; ó
    - simplemente y mucho mas facil, un flag que si uno entra a Turing y lo corre con eso, pushea a pesar del !TodoOK. <br>
En cualquiera de los 2 casos igual involucraria ir a Turing para poder tenerlo.

2. No se podría de alguna relacionar a las No-Entregas? O esas estan reservadas enteramente al caso de que no tengan codigo enviable.

**Comment by dato** [comment]
El punto 1 ya se puede hacer, y no hace falta turing.

El script puede correr en cualquier sito que haya un checkout de algo2_entregas, y sincronizaría el último estado. (El check del "todo OK" está en corrector.py; el script-módulo pull_requests.py no sabe _nada_ de todo OK; es agnóstico, no parsea nada.)

El punto 2 se mete ya con el sistema de entregas. Las no-entregas sí son para código viable. Pero capaz una mejor UI que "el docente tiene que correr el corrector a mano", podría ser "el docente le pide al alumno, envíalo de nuevo y haz click en el check-box 'forzar actualización de PR'", sería lindo pero habría que programarlo. De momento, lo bueno es que el 1 se podría hacer, sin turing, y con poco esfuerzo.

(Gracias por comentar.)

**Comment by dato** [comment]
(Lo único que tampoco me gusta de esto es que se pierde la idempotencia, pero bueno. A la vez, ahora mismo el push al PR no se hace fallo a fallo. De hecho, hasta el primer push no se pushea nada; segundo, las actualizaciones "llegan" al PR solo cuando hay un nuevo Todo OK.)

**Comment by dato** [comment]
Actualización: a día de hoy corrector.py está sincronizando no solo cada entrega en un commit separado, sino que —como experimento para el nuevo corrector basado en Github— también está sincronizando en cada entrega, y no solo en Todo OK.

No recibí feedback negativo sobre este punto de Mati/Nacho/Martín, así que creo que va a quedar así: se sincroniza todo, de manera inmediata.

(Respecto a las NoEntregas, creo que no hace falta UI en el sistema de entregas, pueden poner un comentario "Subo código tal y como me pidió mi corrector".)
