### ISSUE TITLE
Enviar link (a repo/prs/lo que fuere) de aquellos que tienen repo asociado

### ISSUE THREAD

**Issue by mbuchwald** [algoritmos-rw/corrector#48]
En cualquier entrega Todo OK, enviar el link (para tener más a mano)

**Comment by dato** [comment]
Esto está live con los últimos cambios en #42.

(A cambio, yo se envía la URL exacta para el pull request. Pero la URL que se envía incluye el branch, por lo tanto solo hay que darle al botón que figura allí mismo, bastante visible, `New pull request`).
