### ISSUE TITLE
Jubilar id_cursada()

### ISSUE THREAD

**Issue by dato** [algoritmos-rw/corrector#53]
(Por motivos obvios.)

https://github.com/algoritmos-rw/corrector/blob/9ab64d60b5e3e4cb9d595a481112282e138038b3/corrector.py#L230-L243

**Comment by mbuchwald** [comment]
Para mi esta bien que exista la función :P luego de dónde saca esta info es otra cosa, je

**Comment by dato** [comment]
De momento he hecho un hot fix en turing devolviendo simplemente `"2020_1"`, porque esto ya entraba en efecto pasado mañana.

**Comment by dato** [comment]
Maravilloso.

**Comment by colltoaction** [comment]
Realmente eres el rey de reyes
